
name: family_tracker_background
description: Family Tracker with Background Location

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  firebase_core: ^2.25.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.0
  flutter_background_service: ^5.0.5
  location: ^5.0.0

flutter:
  uses-material-design: true
